# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ChemCal',
                'doc_host': 'https://Rhys-McAlister.github.io',
                'git_url': 'https://github.com/Rhys-McAlister/ChemCal',
                'lib_path': 'ChemCal'},
  'syms': {'ChemCal.core': {'ChemCal.core.foo': ('core.html#foo', 'ChemCal/core.py')}}}
